on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    name: A job to run the workflow
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run the workflow using the local code
        uses: ./ # Uses an action in the root directory
        id: vape-naysh
        with:
          base-url: "https://api-vs.***REMOVED***.us"
          environment: "***REMOVED***"
      # Use the output from the `hello` step
      #- name: Get the output time
      #  run: echo "The time was ${{ steps.hello.outputs.time }}"
